baseURL = "https://example.com"
title = "Your Awesome Website"
theme = "hugo-theme-robotico"
paginate = 3

[params]
description = "A sleek personal website theme"
logofile = "img/robobrand.png"
faviconfile = "img/robobrand.png"
copyright = "Wiley McKay Conte 2018"
github = "wileybaba"
email = "baba@example.com"
twitter = "wiley_baba"
instagram = "wileybaba"
fork = "github.com/wileybaba/Robotico_hugo_theme"
progressively = true
defaultContentLanguage = 'en'

# Menus

[languages]
  [languages.en]
  languageCode = "en-us"
    [[languages.en.menu.primary]]
    identifier = "code"
    name = "code"
    url = "https://github.com/wileybaba"
    weight = 10

    [[languages.en.menu.primary]]
    identifier = "portfolio"
    name = "portfolio"
    url = "/portfolio/"
    weight = 20

    [[languages.en.menu.primary]]
    identifier = ""

    [[languages.en.menu.primary]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 30

    [[languages.en.menu.secondary]]
    identifier = "patreon"
    name = "Patreon"
    url = "https://www.patreon.com/bePatron?u=10637849"
    weight = 110

    [[languages.en.menu.secondary]]
    identifier = "bmc"
    name = "Buy me a coffee"
    url = "https://www.buymeacoffee.com/wiley"
    weight = 120

  [languages.es]
  languageCode = "es-us"
    [[languages.es.menu.primary]]
    identifier = "codigo"
    name = "codigo"
    url = "https://github.com/wileybaba"
    weight = 10

    [[languages.es.menu.primary]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 20

    [[languages.es.menu.primary]]
    identifier = ""

    [[languages.es.menu.secondary]]
    identifier = "patreon"
    name = "Patreon"
    url = "https://www.patreon.com/bePatron?u=10637849"
    weight = 110

    [[languages.es.menu.secondary]]
    identifier = "bmc"
    name = "Comprame Un Cafe"
    url = "https://www.buymeacoffee.com/gokmen"
    weight = 120

# Gallery 

  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=251"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=252"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=253"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=254"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=255"
  [[params.portfolio]]
  link = "https://picsum.photos/1200/768.jpg?image=256"
